server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/finance?characterEncoding=utf8&useSSL=false
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      timeout: 3000ms
  mail:
    username: turbo10240@163.com
    password: 
    host: smtp.163.com
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: logs/app.log
  level:
    root: info